/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WiseRouteImport } from './routes/wise'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'

const WiseRoute = WiseRouteImport.update({
  id: '/wise',
  path: '/wise',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expenses': typeof ExpensesRoute
  '/onboarding': typeof OnboardingRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/salary': typeof SalaryRoute
  '/wise': typeof WiseRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expenses': typeof ExpensesRoute
  '/onboarding': typeof OnboardingRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/salary': typeof SalaryRoute
  '/wise': typeof WiseRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expenses': typeof ExpensesRoute
  '/onboarding': typeof OnboardingRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/salary': typeof SalaryRoute
  '/wise': typeof WiseRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/expenses'
    | '/onboarding'
    | '/receipts'
    | '/reports'
    | '/salary'
    | '/wise'
    | '/accounts/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/expenses'
    | '/onboarding'
    | '/receipts'
    | '/reports'
    | '/salary'
    | '/wise'
    | '/accounts/$accountId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/expenses'
    | '/onboarding'
    | '/receipts'
    | '/reports'
    | '/salary'
    | '/wise'
    | '/accounts/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExpensesRoute: typeof ExpensesRoute
  OnboardingRoute: typeof OnboardingRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ReportsRoute: typeof ReportsRoute
  SalaryRoute: typeof SalaryRoute
  WiseRoute: typeof WiseRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wise': {
      id: '/wise'
      path: '/wise'
      fullPath: '/wise'
      preLoaderRoute: typeof WiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExpensesRoute: ExpensesRoute,
  OnboardingRoute: OnboardingRoute,
  ReceiptsRoute: ReceiptsRoute,
  ReportsRoute: ReportsRoute,
  SalaryRoute: SalaryRoute,
  WiseRoute: WiseRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
